### ISSUE TITLE
Review use of offensive language

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/katacoda-scenarios#14]
Review repo for offensive langauge

 * https://github.com/github/renaming
```
git grep -I -E 'master|slave|whitelist|blacklist' -- ':!vendor' ':!cluster-up' ':!cluster-sync' ':!*generated*'
```

**Comment by cwilkers** [comment]
Most of this is due to a need to rename the repo's primary branch, but I see several mentions of "master" in the markdown of the scenarios where they employ the older k8s cluster nomenclature for control/worker nodes which has been changed. I will update.
