### ISSUE TITLE
katacoda is no longer available

### ISSUE THREAD

**Issue by iranzo** [kubevirt/katacoda-scenarios#34]
Katacoda is no longer available, move to alternatives like killercoda or others (https://itnext.io/katacoda-to-killercoda-migration-guide-d21961fc0c9b)

**Comment by aburdenthehand** [comment]
@cwilkers - FYI

**Comment by cwilkers** [comment]
The initial two (101 and CDI) labs have been moved over to killercoda, plumbing on the website is still needed.
