### ISSUE TITLE
Update Killercoda scenarios from deprecated k3s profiles

### ISSUE THREAD

**Issue by cwilkers** [kubevirt/katacoda-scenarios#46]
Email from Killercoda:

We're writing you because you've some scenarios based on K3s environments.

As recently announced these have been deprecated. Please check here for more details and how to migrate.

We suggest to go ahead and change your imageid to "kubernetes-kubeadm-1node" or "kubernetes-kubeadm-1node-4GB".

From the 20.01.2024, all K3s scenarios will automatically be run on corresponding Kubeadm environments. If you don't rely on K3s specifically, nothing should break.

You could also use our "ubuntu" environments and install K3s yourself in foreground or background scripts.

**Comment by wuestkamp** [comment]
It looks like the scenarios on https://killercoda.com/kubevirt are currently broken.
I'll remove KubeVirt from the Killercoda main page for now, will add again once fixed.
Will follow this issue and repo.
Let me know if you need help!

**Comment by cwilkers** [comment]
Looking into it this morning, it seems my assumptions about how k3s installs were broken by a change. I've changed my "Is k3s installed yet?" test to look for a kubeconfig, not the binary. Will PR shortly.
